# Práctica 1.1 — Probabilidad y Estadística
## Análisis de la evolución poblacional mundial
### Deborah Villicaña Prieto

Objetivo: Reconocer la procedencia del conjunto de datos antes de utilizarlo y documentar correctamente su fuente.

Los datos utilizados en esta práctica provienen de **Our World in Data (OWID)**.

La fuente original es **United Nations, World Population Prospects (2024)**.
**Cita:**
> UN, World Population Prospects (2024) – processed by Our World in Data. “Annual change in population – UN WPP” [dataset]. United Nations, “World Population Prospects”; United Nations, “World Population Prospects - Interim Update” [original data].

Preguntas:
1.	¿Quién produjo originalmente los datos? La ONU.
2.	¿Qué organización los procesa para su utilización en Our World in Data? Global Change Data Lab
3.	¿Qué representa la variable que analizarás? La variable "Annual Change in Population" representa el cambio anual de la población de cada país. Con esto se puede sabaer si está incrementando o disminuyendo.



# Actividad 2 - Carga y exploración de datos
## Objetivo: Comprobar que el entorno de Python, Pandas y Jupyter funciona correctamente y realizar una primera exploración del dataset.

In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv("C:\\Users\\debor\\Documents\\Deborah\\ISSC\\5to\\Big Data\\U1_1_probabilidad_estadistica\\data\\raw\\annual-population-growth\\annual-population-growth.csv")

In [3]:
df.head(3)

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN


In [4]:
#Extracción de datos.
df["Entity"]

0        Afghanistan
1        Afghanistan
2        Afghanistan
3        Afghanistan
4        Afghanistan
            ...     
38395       Zimbabwe
38396       Zimbabwe
38397       Zimbabwe
38398       Zimbabwe
38399       Zimbabwe
Name: Entity, Length: 38400, dtype: str

In [5]:
df.shape

(38400, 5)

In [6]:
df.dtypes

Entity                                      str
Code                                        str
Year                                      int64
Annual change in population             float64
Annual population change (Projected)    float64
dtype: object

In [7]:
df.columns.tolist()

['Entity',
 'Code',
 'Year',
 'Annual change in population',
 'Annual population change (Projected)']

In [8]:
df.describe()

,Year,Annual change in population,Annual population change (Projected)
count,38400.000000,1.868800e+04,1.971200e+04
mean,2025.500000,2.063019e+06,8.375481e+05
std,43.300872,9.440859e+06,5.816745e+06
min,1951.000000,-3.315935e+06,-2.291035e+07
25%,1988.000000,1.781000e+03,-9.742750e+03
50%,2025.500000,4.689800e+04,9.350000e+01
75%,2063.000000,3.021128e+05,1.411160e+05
max,2100.000000,9.337137e+07,7.206736e+07


In [9]:
df.isnull().sum()

Entity                                      0
Code                                     1200
Year                                        0
Annual change in population             19712
Annual population change (Projected)    18688
dtype: int64

In [10]:
df["Entity"].unique() #Muestra todos los datos únicos

<StringArray>
[        'Afghanistan',         'Africa (UN)',             'Albania',
             'Algeria',      'American Samoa',       'Americas (UN)',
             'Andorra',              'Angola',            'Anguilla',
 'Antigua and Barbuda',
 ...
             'Vanuatu',             'Vatican',           'Venezuela',
             'Vietnam',   'Wallis and Futuna',      'Western Sahara',
               'World',               'Yemen',              'Zambia',
            'Zimbabwe']
Length: 256, dtype: str

In [11]:
df["Entity"].nunique() #CUENTA los datos únicos

256

In [12]:
#Filtrar año 2020 y se asigna a un nuevo DataFrame
df_2020 = df[df["Year"]==2020]
df_2020.head(3)

#Los índices corresponden al df original

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
69,Afghanistan,AFG,2020,1212852.0,NaN
219,Africa (UN),UN_AFR,2020,32815675.0,NaN
369,Albania,ALB,2020,-13061.0,NaN


In [13]:
df_2020_ext_col1 = df_2020[["Entity", "Year"]]
df_2020_ext_col1.head(3)

#de manera simplificada en una sola línea
df_2020_ext_col2 = df[df["Year"]==2020][["Entity", "Year"]]
df_2020_ext_col2.head(3)

,Entity,Year
69,Afghanistan,2020
219,Africa (UN),2020
369,Albania,2020


In [14]:
#Rango de fechas
df_2005_2020 = df[(df["Year"]>= 2005)&(df["Year"] <=2020)]
df_2005_2020.head(3)
#df_2005_2020.shape


,Entity,Code,Year,Annual change in population,Annual population change (Projected)
54,Afghanistan,AFG,2005,843919.0,NaN
55,Afghanistan,AFG,2006,1019525.0,NaN
56,Afghanistan,AFG,2007,485752.0,NaN


In [15]:
df_2005_2020_mx = df[(df["Year"]>= 2005) & (df["Year"] <=2020) & (df["Entity"]=="Mexico")]
df_2005_2020_mx.shape

(16, 5)

In [16]:
df_ext_EA = df_2005_2020_mx[["Entity", "Annual change in population"]]
df_ext_EA.head(3)

,Entity,Annual change in population
22254,Mexico,1417373.0
22255,Mexico,1442162.0
22256,Mexico,1520690.0


In [17]:
df_ext_EA.mean(numeric_only=True)

Annual change in population    1400307.625
dtype: float64

1.	¿Cuántas filas y columnas tiene el dataset? 38400 filas, 5 columnas
2.	¿Qué tipo de datos contiene la variable Year? int64
3.	¿Existen valores faltantes? Sí, en Code, Annual change in population y Annual population change (Projected)
4.	¿Cuántas entidades diferentes contiene el dataset? 256


# Actividad 3 - Estadística Descriptiva

In [18]:
#país primer apellido: Vietnam
df_vietnam = df[(df["Entity"] =="Vietnam") & (df["Year"] >= 1983) & (df["Year"] <= 2021)]
df_vietnam.describe()

,Year,Annual change in population,Annual population change (Projected)
count,39.000000,3.900000e+01,0.0
mean,2002.000000,1.126252e+06,NaN
std,11.401754,2.102038e+05,NaN
min,1983.000000,7.493320e+05,NaN
25%,1992.500000,9.914570e+05,NaN
50%,2002.000000,1.106511e+06,NaN
75%,2011.500000,1.295271e+06,NaN
max,2021.000000,1.542415e+06,NaN


In [19]:
#Variable: "Annual change in population" cual pais tiene el min y max de cambio en poblacion anual
df_acp = df[["Entity", "Annual change in population"]]
df_acp.min(numeric_only=True)



Annual change in population   -3315935.0
dtype: float64

In [20]:
df_acp.max()

Entity                           Zimbabwe
Annual change in population    93371370.0
dtype: object

In [21]:
df_acp.median(numeric_only=True)

Annual change in population    46898.0
dtype: float64

In [22]:
df_acp = df[df["Entity"] == "Ukraine"]
df_acp.min()

Entity                                    Ukraine
Code                                          UKR
Year                                         1951
Annual change in population            -3315935.0
Annual population change (Projected)    -376640.0
dtype: object

In [23]:
df_acp_min = df_acp[df_acp["Annual change in population"] == -3315935.0]
df_acp_min

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
35772,Ukraine,UKR,2023,-3315935.0,NaN


Preguntas
Responde brevemente:
1.	¿Cuál es el valor de la media? 1.126252e
2.	¿Cuál es el valor de la mediana? 46898.0
3.	¿Cuál es el valor de la desviación estándar? 2.102038e
4.	¿Qué entidad presenta el valor mínimo y cuál el máximo? Ukraine el mínimo y Zimbabwe el máximo


# Actividad 4
Propósito:
Comprobar que el notebook está utilizando correctamente las herramientas configuradas para la práctica.


In [24]:
import sys

print("Python:", sys.version)
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)


Python: 3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)]
Pandas: 3.0.5
NumPy: 2.5.2


# Ejercicios loc iloc

In [25]:
df.iloc[:,0:2]

,Entity,Code
0,Afghanistan,AFG
1,Afghanistan,AFG
2,Afghanistan,AFG
3,Afghanistan,AFG
4,Afghanistan,AFG
...,...,...
38395,Zimbabwe,ZWE
38396,Zimbabwe,ZWE
38397,Zimbabwe,ZWE
38398,Zimbabwe,ZWE


In [26]:
df.loc[10000]


Entity                                  Equatorial Guinea
Code                                                  GNQ
Year                                                 2051
Annual change in population                           NaN
Annual population change (Projected)              46407.0
Name: 10000, dtype: object

In [27]:
df.loc[:, ["Entity", "Year", "Annual change in population"]] #: porque quiero que muestre todas las filas

,Entity,Year,Annual change in population
0,Afghanistan,1951,103163.0
1,Afghanistan,1952,108441.0
2,Afghanistan,1953,108919.0
3,Afghanistan,1954,111251.0
4,Afghanistan,1955,119027.0
...,...,...,...
38395,Zimbabwe,2096,NaN
38396,Zimbabwe,2097,NaN
38397,Zimbabwe,2098,NaN
38398,Zimbabwe,2099,NaN


In [28]:
df.iloc[:, [0,2,3]] #orden entre corchetes: filas, columnas

,Entity,Year,Annual change in population
0,Afghanistan,1951,103163.0
1,Afghanistan,1952,108441.0
2,Afghanistan,1953,108919.0
3,Afghanistan,1954,111251.0
4,Afghanistan,1955,119027.0
...,...,...,...
38395,Zimbabwe,2096,NaN
38396,Zimbabwe,2097,NaN
38397,Zimbabwe,2098,NaN
38398,Zimbabwe,2099,NaN


In [29]:
df.loc[10000, ["Entity", "Year", "Annual change in population"]]

Entity                         Equatorial Guinea
Year                                        2051
Annual change in population                  NaN
Name: 10000, dtype: object

In [30]:
df.iloc[10000, [0,2,3]]

Entity                         Equatorial Guinea
Year                                        2051
Annual change in population                  NaN
Name: 10000, dtype: object

In [31]:
df.loc[(df["Entity"] == "Mexico") & (df["Year"] == 2020)]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22269,Mexico,MEX,2020,1036075.0,NaN


In [32]:
df.set_index("Entity")
df.head

<bound method NDFrame.head of             Entity Code  Year  Annual change in population  \
0      Afghanistan  AFG  1951                     103163.0   
1      Afghanistan  AFG  1952                     108441.0   
2      Afghanistan  AFG  1953                     108919.0   
3      Afghanistan  AFG  1954                     111251.0   
4      Afghanistan  AFG  1955                     119027.0   
...            ...  ...   ...                          ...   
38395     Zimbabwe  ZWE  2096                          NaN   
38396     Zimbabwe  ZWE  2097                          NaN   
38397     Zimbabwe  ZWE  2098                          NaN   
38398     Zimbabwe  ZWE  2099                          NaN   
38399     Zimbabwe  ZWE  2100                          NaN   

       Annual population change (Projected)  
0                                       NaN  
1                                       NaN  
2                                       NaN  
3                                       N